# Generated by Django 3.1.2 on 2021-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('posted_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('claims_left', models.PositiveIntegerField()),
            ],
        ),
    ]
