# Generated by Django 3.1.2 on 2021-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
