# Generated by Django 3.1.2 on 2021-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
