# Generated by Django 3.1 on 2021-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_merge_20210322_2138'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeems',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='redeems',
            unique_together={('voucher', 'student')},
        ),
    ]
