# Generated by Django 3.1.2 on 2021-04-05 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='email_list',
            field=models.FileField(default=django.utils.timezone.now, upload_to='emails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code_list',
            field=models.FileField(default=django.utils.timezone.now, upload_to='codes'),
            preserve_default=False,
        ),
    ]
