# Generated by Django 3.1.2 on 2021-04-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_idcodeemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcodeemail',
            old_name='voucher_id',
            new_name='voucher',
        ),
        migrations.AlterField(
            model_name='idcodeemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.email'),
        ),
    ]
