# Generated by Django 3.1.2 on 2021-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20210405_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='email_list',
            field=models.FileField(blank=True, null=True, upload_to='emails'),
        ),
    ]
