# Generated by Django 3.1.2 on 2021-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20210217_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.ImageField(default=None, upload_to='assets'),
            preserve_default=False,
        ),
    ]
