# Generated by Django 3.1.2 on 2021-03-18 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_voucher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code_list',
            field=models.FileField(default=django.utils.timezone.now, upload_to='codes'),
            preserve_default=False,
        ),
    ]
