# Generated by Django 3.1.2 on 2021-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_code_isassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='isAssigned',
            field=models.BooleanField(default=False),
        ),
    ]
