# Generated by Django 3.1.2 on 2021-03-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_voucher_code_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='code_list',
        ),
    ]
