# Generated by Django 3.1.6 on 2021-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20210418_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
