# Generated by Django 3.1.6 on 2021-04-24 09:32

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_voucher_code_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
