# Generated by Django 3.1 on 2021-03-22 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_auto_20210320_1158'),
    ]

    operations = [
    ]
