# Generated by Django 3.1.6 on 2021-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_auto_20210424_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
