# Generated by Django 3.1.2 on 2021-03-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='claims_left',
            new_name='counter',
        ),
    ]
