# Generated by Django 3.1 on 2021-03-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20210322_1505'),
        ('voucher', '0009_auto_20210322_1702'),
    ]

    operations = [
    ]
