# Generated by Django 3.1 on 2021-03-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20210322_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='email_list',
            field=models.FileField(blank=True, null=True, upload_to='emails'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
        ),
    ]
