# Generated by Django 3.1 on 2021-03-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('voucher', '0011_merge_20210322_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_to_organization', to='organization.organization'),
        ),
    ]
