# Generated by Django 3.1 on 2021-03-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20210322_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='email_list',
            field=models.FileField(null=True, upload_to='emails'),
        ),
    ]
