# Generated by Django 3.1 on 2021-03-26 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_merge_20210322_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
