# Generated by Django 3.1 on 2021-03-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_auto_20210327_1611'),
        ('voucher', '0011_auto_20210327_1836'),
    ]

    operations = [
    ]
