# Generated by Django 3.1.2 on 2021-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='eligible_faculties',
            field=models.CharField(default='', max_length=255),
        ),
    ]
