# Generated by Django 3.1.2 on 2021-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_voucher_eligible_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='eligible_faculties',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
