# Generated by Django 3.1.2 on 2021-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20210409_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='isAssigned',
            field=models.BooleanField(default=True),
        ),
    ]
