# Generated by Django 3.1.6 on 2021-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_remove_email_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets'),
        ),
    ]
