# Generated by Django 3.1 on 2021-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
