# Generated by Django 3.1.2 on 2021-10-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_to_student', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nusnet_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('year', models.PositiveIntegerField()),
                ('organizations', models.ManyToManyField(related_name='students_organizations', through='student.InOrganization', to='organization.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='inorganization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_organization', to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='inorganization',
            unique_together={('organization', 'student')},
        ),
    ]
