# Generated by Django 3.1.2 on 2022-02-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220219_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organizations',
        ),
    ]
