# Generated by Django 3.1.2 on 2021-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210711_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='nusnet_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
