# Generated by Django 3.1.2 on 2022-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('student', '0003_auto_20220219_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organizations',
            field=models.ManyToManyField(related_name='students_organizations', through='student.InOrganization', to='organization.Organization'),
        ),
    ]
